from node:alpine

WORKDIR '/app'

COPY package.json .

ENV HTTPS_PROXY "http://127.0.0.1:3128"
ENV HTTP_PROXY "http://127.0.0.1:3128"

RUN npm config set http-proxy http://docker.for.win.localhost:3128
run npm config set https-proxy http://docker.for.win.localhost:3128

RUN npm install

COPY . .

CMD ["npm", "run", "start"]